title: Ahmad's Amazing Website!!!
author: AhmadRajab
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is an amzaing web site with Ahmad's cool stuff

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
